### ISSUE TITLE
On 1.1.5, dotnet Source-Generated client doesn't appear to work

### ISSUE THREAD

**Issue by b4ux1t3** [clockworklabs/SpacetimeDB#2811]
Working my way through the quickstart, I got the server running just fine. I've vetted that it runs and can perform actions in the DB.

However, I ran into issues trying to get the client spun up.

Now, admittedly I started out by trying to build a service for the client, and not _directly_ using the code from the guide. Eventually, once everything was "running", I ran into this runtime reflection error:

```
System.MissingMethodException: Method not found: 'System.Object SpacetimeDB.BSATN.IStructuralReadWrite.GetSerializer()'.
   at SpacetimeDB.DbConnectionBase`3..ctor()
   at SpacetimeDB.Types.DbConnection..ctor() in /home/alex/projects/spacetime/stdb-qs-chat/QuickstartChat.Client.Cli/module_bindings/SpacetimeDBClient.g.cs:line 458
   at System.RuntimeType.CreateInstanceOfT()
```

Initially, I tried to use dotnet conventions for folder names (`ModuleBindings` instead of `module_bindings`), but I've backed everything out to, literally, copy-pasted code from the quickstart guide and I continue to see this on both Mac and Linux. (Before it's asked, yes, I have tried to regen the bindings on both systems at every step.)

This is on dotnet 8.0.405 on Linux Mint and 8.0.400 on MacOS.

Note that this is only if I use `SpacetimeDB.ClientSDK@1.1.5`. If I roll back to `1.1.1`, I don't have this issue.

**Comment by theodor349** [comment]
I am experiencing the same issue with `SpacetimeDB.ClientSDK@1.1.5` causing the described error. Downgrading to `1.1.1` successfully resolves the problem for me as well.

My server runs without any issues, and I am able to interact with it using the CLI without any problems.

Here are my environment details:
- Dotnet SDK: `8.0.410`
- MacOS: `Version 15.5 (24F74)`
- Spacetimedb tool version `1.1.2` and spacetimedb-lib version `1.1.2`

**Comment by bfops** [comment]
Thank you for flagging this! Unfortunately, the bump to `1.1.5` actually also required a bump to `SpacetimeDB.Runtime`, but this doesn't happen automatically when projects have already fetched a previous version of `SpacetimeDB.Runtime`.

I believe if you clear enough caches in enough places, you can force it to fetch the latest version of that library.

Alternatively, I believe it can also be fixed by explicitly adding this to your `.csproj`, to force an upgrade:
```
    <PackageReference Include="SpacetimeDB.Runtime" Version="1.1.2" />
```

You shouldn't need this line once it's working (or in the future).

Sorry for the mess!

**Comment by b4ux1t3** [comment]
@bfops Absolutely no worries on my end. Just wanted to make sure to get it reported! Super excited to play around with this, thank you all for your excellent work.

**Comment by agearhart** [comment]
I was testing out a sample project and have reproduced the same issue with https://github.com/agearhart/learn-spacetimedb.  The server side is running fine with the CLI.  The client can build, but fails on launch with the same stack.

https://github.com/agearhart/learn-spacetimedb

**Comment by theodor349** [comment]
I have:
- Added ` <PackageReference Include="SpacetimeDB.Runtime" Version="1.1.2" />` to the `StdbModule` project
- Cleaned all nuget caches with `dotnet nuget locals all --clear`
- Removed all `obj` and `bin` folders

However, I still get the same error.

**Comment by bfops** [comment]
@theodor349 Rats. Sorry for the red herring.

We're planning to release 1.2.0 in the next day or two, so maybe the quickest path forward is to wait for that instead of continuing to debug. It should fix the issue since it will force a requirement for `SpacetimeDB.Runtime` at `1.2.0` as well.

I wish I had something more helpful to say!

**Comment by theodor349** [comment]
@bfops no worries. The older version works fine for now. 

I will be looking forward to next version.

**Comment by miatribe** [comment]
just adding `<PackageReference Include="SpacetimeDB.Runtime" Version="1.1.2" />` to the client.csproj and rerunning `dotnet run --project client` has fixed the issue for me.

**Comment by bfops** [comment]
Ah sorry, to post an update here - we've delayed the 1.2.0 release a bit to include some more bugfixes. Expecting it now on Tuesday. Sorry for the delay!

**Comment by b4ux1t3** [comment]
I intend to take a look at this this week to see if it's resolved.

Thanks for the heads up on the release!

**Comment by bfops** [comment]
This is hopefully resolved since that release! Please reopen if you're still having issues.
